### ISSUE TITLE
logging.debug(mem_top()) is not defined

### ISSUE THREAD

**Issue by helarsen** [denis-ryzhkov/mem_top#3]
I have installed with pip and import part works, but the result of logging.debug(mem_top()) is

_File "<stdin>", line 1, in <module> NameError: name 'logging' is not defined._

What am I missing? A full working example would be nice to get started on. 
thanks

**Comment by denis-ryzhkov** [comment]
Sorry, but teaching you basics of Python is out of scope. RTFM https://docs.python.org/2/library/logging.html
