### ISSUE TITLE
refs

### ISSUE THREAD

**Issue by jimanvlad** [denis-ryzhkov/mem_top#4]
Hi,

Can you please explain what "refs" refer to?

I am trying to use your module to identify a memory leak in my application. 

If "refs" are just the amount of time an object is referenced, that shouldn't be an issue. If "refs" is an indicator of duplication in the memory (identical object created x times), that's a much more potent indicator.

Vlad

**Comment by jimanvlad** [comment]
Also, is it possible to display how much memory is allocated to that particular line? 

e.g. 18948   <type 'dict'> <5Mb +1Mb> {...

**Comment by denis-ryzhkov** [comment]
Hi,

"refs" is a number of objects, referenced by this object.

https://docs.python.org/2/library/gc.html#gc.get_referents

E.g. if you are adding items to some dict, or to an object that has no "len", its "refs" will be growing. Big numbers may be a clue of a leak.

I will try to add size in bytes, good idea, thanks.

**Comment by denis-ryzhkov** [comment]
Added "bytes" top, please `pip install -U mem_top`

Added "see also" links:
* https://docs.python.org/2/library/gc.html#gc.garbage
* https://pypi.python.org/pypi/objgraph
