### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by ad-m** [denis-ryzhkov/mem_top#5]
Hello,

I suggest provide command-line interface like [memory_profiler](https://pypi.python.org/pypi/memory_profiler) or cProfile to start some python script and from time to time printing stats.

Greetings,

**Comment by denis-ryzhkov** [comment]
Hello @ad-m! Sorry for huge delay: notifications were disabled for some reason. Thank you for this idea.

I looked into [how this is implemented in memory_profiler](https://github.com/pythonprofilers/memory_profiler/blob/eed3447369e5b0cd708de045b757e0bac853a83b/memory_profiler.py#L1233) and it looks like an overkill for `mem_top`.

Also, I don't want to make any assumptions on how `mem_top` should intercept control from time to time: either greenlets or threads or whatever else is used in the app under the test.

It's better for the app to decide where and how often to log `mem_top` safely.

However, if you can implement it in a simple and safe way, please post a PR and reopen this issue.
