### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by fabiopedrosa** [denis-ryzhkov/mem_top#6]
Can you publish the 0.1.7 for python3?

https://pypi.org/simple/mem-top/

**Comment by denis-ryzhkov** [comment]
Hi @fabiopedrosa! Sorry for huge delay: notifications were disabled for some reason.
Thank you for noticing py3 issue!
I've published an updated version - you may find `mem_top-0.2.1-py3-none-any.whl` in the https://pypi.org/simple/mem-top/
